version: '3'

services:
  quoteservice:
    environment:
      JAVA_OPTS: -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n
      JDBCURL: jdbc:postgresql://new-merchant-quote-service-rds.local.com:5432/quote
      JDBCUSERNAME: postgres
      JDBCPASSWORD: postgres
    ports:
      - 8000:8000
      - 8080:8080
    image: new-merchant-quote-service-api
    networks:
      app_net:
        ipv4_address: 172.19.2.20

  quotedb:
    image: postgres:10
    environment:
          - "POSTGRES_PASSWORD=postgres"
          - "POSTGRES_USER=postgres"
          - "POSTGRES_DB=quote"
    networks:
      app_net:
        aliases:
          - new-merchant-quote-service-rds.local.com
        ipv4_address: 172.19.2.97

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.2.0/24
      driver: default